git add   CHANGES
git add   FUTURES
git add   Makefile
git add   PROBLEMS
git add   README
git add   alloca.c
git add   alloca.s
git add   array.c
git add   awk.h
git add   awk.y
git add   builtin.c
git add   eval.c
git add   field.c
git add   gawk.1
git add   gawk.texinfo
git add   io.c
git add   main.c
git add   missing.c
git add   msg.c
git add   node.c
git add   patchlevel.h
git add   regex.c
git add   regex.h
git add ACKNOWLEDGMENT
git add LIMITATIONS
git add Makefile-dist
git add PORTS
git add README.VMS
git add README.dos
git add README.rs6000
git add README.ultrix
git add atari
git add awk.tab.c
git add config.h
git add config.h-dist
git add config
git add configure
git add dfa.c
git add dfa.h
git add foo.sh
git add iop.c
git add mkconf
git add mungeconf
git add pc/config.h
git add pc/make.bat
git add pc/names.lnk
git add protos.h
git add re.c
git add version.c
git add vms
